Homework 7
kdr1mkf/IgorShabanov pull request #7
Opened 2021-08-30 04:49 UTC by kdr1mkf

Homework 7 seems to be done.

2021-09-01 17:26 UTC, pnatashap requested changes
Comments are in a code

2021-09-01 17:26 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/components/HeaderMenu.java
> +    @UI("//*[contains(@class, \"m-l8\")]//*[contains(text(), \"Metals & Colors\")]")
Locator is very difficult. 
The correct way is to write locator for header and simple locator for page by text

2021-09-01 17:26 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/components/LogInForm.java
> +    public void logIn(User user) {
This function is not for Form. Fullname is not a part of the form, so we break the logic.

2021-09-01 17:26 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/components/LogInForm.java
> +            name.setValue(user.getName());
There is a function loginAs in Form, it's a part of that function that we can just use

2021-09-01 17:26 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/components/LogInForm.java
> +    protected static Button userIcon;
This is not a part of Form

2021-09-01 17:26 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/domain/DataSet.java
> +public class DataSet extends DataClass<DataSet> {
DataSet is a very common name, it's better to rename it

2021-09-01 17:26 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/page/JdiLightSite.java
> +    public static void fillMetalsAndColorsForm(DataSet dataSet) {
This function cann't be a part of Site. At this place we can only create a functions that can be used in ANY page

2021-09-01 17:26 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/page/JdiLightSite.java
> +    public static List<String> getResultMessages() {
This function cann't be a part of Site. At this place we can only create a functions that can be used in ANY page

2021-09-01 17:26 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/page/JdiLightSite.java
> +    public static void submitMetalsAndColorsForm() {
This function cann't be a part of Site. At this place we can only create a functions that can be used in ANY page

2021-09-01 17:26 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/MetalsAndColorsFormTest.java
> +        JdiLightSite.logIn(user);
Login is not a part of the test, it's a precondition

2021-09-02 04:40 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/test/MetalsAndColorsFormTest.java
> +        JdiLightSite.logIn(user);
LogIn is not a precondition. Log in is marked as a step of the test  in the task. My approach meets the task.
![login-as-step](https://user-images.githubusercontent.com/64832324/131782747-458d783c-8c1b-469c-8411-c0e2ecddd66c.png)

2021-09-02 05:06 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/components/HeaderMenu.java
> +    @UI("//*[contains(@class, \"m-l8\")]//*[contains(text(), \"Metals & Colors\")]")
I see no any kind of "difficulty" in the locator. Anyway, it's fixed.

2021-09-02 06:12 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/components/LogInForm.java
> +    protected static Button userIcon;
Fixed.

2021-09-02 06:12 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/domain/DataSet.java
> +public class DataSet extends DataClass<DataSet> {
Fixed.

2021-09-02 08:00 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/components/LogInForm.java
> +            name.setValue(user.getName());
The comment above says 
>  this function is not for Form

This comment says
>  There is a function loginAs in Form

Don't these comments break the logic?

loginAs brings me another problem. loginAs tryes to find and fill "fullName" field. I have no idea where I'm supposed to store the fullName attribute that belongs to a User entitiy. If I'm supposed to override loginAs logic anyway, why do I need loginAs then?

2021-09-02 08:00 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/page/JdiLightSite.java
> +    public static void fillMetalsAndColorsForm(DataSet dataSet) {
We can use that function at any place of the site. It throws an exception if the method is used in the wrong way. How am I supposed to interract with pages? Direct access to the class attributes violates incapsulation.
Direct access provides the opportunity to use any method at any page and does not solve the mentioned problem.

2021-09-02 08:01 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/page/JdiLightSite.java
> +    public static List<String> getResultMessages() {
We can use that function at any place of the site. It throws an exception if the method is used in the wrong way. How am I supposed to interract with pages? Direct access to the class attributes violates incapsulation.
Direct access provides the opportunity to use any method at any page and does not solve the mentioned problem.

2021-09-02 08:01 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/page/JdiLightSite.java
> +    public static void submitMetalsAndColorsForm() {
We can use that function at any place of the site. It throws an exception if the method is used in the wrong way. How am I supposed to interract with pages? Direct access to the class attributes violates incapsulation.
Direct access provides the opportunity to use any method at any page and does not solve the mentioned problem.

2021-09-02 08:46 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/components/LogInForm.java
> +    public void logIn(User user) {
Fixed.

2021-09-02 17:50 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/components/LogInForm.java
> +            name.setValue(user.getName());
Anyway fixed.

2021-09-03 04:36 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/page/JdiLightSite.java
> +    public static void submitMetalsAndColorsForm() {
Fixed.

2021-09-03 04:36 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/page/JdiLightSite.java
> +    public static List<String> getResultMessages() {
Fixed.

2021-09-03 04:36 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/page/JdiLightSite.java
> +    public static void fillMetalsAndColorsForm(DataSet dataSet) {
Fixed.

2021-09-10 20:45 UTC, pnatashap requested changes
Comments are in code

2021-09-10 20:45 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/page/HomePage.java
> +        fullName.assertThat().displayed();
Function that doesn't use a parameter - bad designed function.
There is no actual assert that this user is loggedIn

2021-09-10 20:45 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/CommonTest.java
> +            .readJsonToListOfObjects(".\\src\\test\\resources\\hw7\\users.json")
Bad practice to read file for EVERY test, operation should be performed only once

2021-09-10 20:45 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/CommonTest.java
> +        JdiLightSite.logIn(user);
If you read a test, you can see that it's not correct to logIn every test. It's better to make sure that we are logged in.

2021-09-11 08:44 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/page/HomePage.java
> +        fullName.assertThat().displayed();
This is the consequence of fixes that were required before.

I can not store user's fullname (JDI fill form feature) in the User class (see requred changes before), so I have no user's fullname. So I can not check if a particular user is logged in.

2021-09-11 08:47 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/test/CommonTest.java
> +            .readJsonToListOfObjects(".\\src\\test\\resources\\hw7\\users.json")
What if I want to run the test for different users?

2021-09-11 08:48 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/test/CommonTest.java
> +        JdiLightSite.logIn(user);
Login that's been performed may influence the next test. I have no information what the "better" is like. I have a test case, that's supposed to be automated and log in is a step.

BTW I do not log in every time. JdiLightSite invokes HomePage method to log in. The HomePage method checks if a user is logged in.

I have no idea what am I supposed to do. Do I have to provide a direct access to the class attributes? Is this a best practice?

2021-09-11 08:56 UTC, kdr1mkf commented on src/test/java/com/epam/tc/hw7/test/CommonTest.java
> +            .readJsonToListOfObjects(".\\src\\test\\resources\\hw7\\users.json")
Whatever.

2021-09-17 21:16 UTC, pnatashap approved these changes

2021-09-19 12:05 UTC, merged